Implement Project Doc Samples
ktorio/ktor-build pull request #3
Opened 2020-10-07 12:47 UTC by Stexxe

Fixes [KTOR-1111](https://youtrack.jetbrains.com/issue/KTOR-1111)

2020-10-07 14:00 UTC, hhariri requested changes

2020-10-07 14:00 UTC, hhariri commented on .teamcity/src/subprojects/build/docsamples/ProjectDocSamples.kt
> +    id("KtorDocs_BuildTest")
Do you think we need Test suffix for this? Cause other build configurations don't have it and it may confuse as if we're building Tests as opposed to building and testing. Also, don't know if it's necessary to explicitly mention the steps covered.

2020-10-07 19:17 UTC, Stexxe commented on .teamcity/src/subprojects/build/docsamples/ProjectDocSamples.kt
> +    id("KtorDocs_BuildTest")
Good point.

2020-10-08 06:07 UTC, hhariri commented on .teamcity/test/VCSTest.kt
> +    fun testSomeRootsHasAuthMethodWithPassword() {
Minor thing but I'd avoid test prefix in tests. I'm not really a fan of test suffix in classes, but I understand for discoverability they may be useful.

2020-10-08 06:08 UTC, hhariri approved these changes

2020-10-08 08:52 UTC, merged