KTOR-2206 Add kotlinx.html publishing configuration
ktorio/ktor-build pull request #58
Opened 2021-03-15 13:43 UTC by e5l

2021-03-15 15:20 UTC, hhariri approved these changes

2021-03-17 07:11 UTC, cy6erGn0m requested changes
We also need a vcs tag labeling build feature

2021-03-17 07:31 UTC, e5l commented
Thanks, will update

2021-03-17 08:15 UTC, e5l commented
Done, please take a look

2021-03-18 07:56 UTC, cy6erGn0m approved these changes

2021-03-18 09:24 UTC, merged